// generated by unplugin-vue-components
// We suggest you to commit this file into source control
// Read more: https://github.com/vuejs/vue-next/pull/3399

declare module 'vue' {
  export interface GlobalComponents {
    AppFooter: typeof import('./../src/components/app/App-Footer.vue')['default']
    AppHeader: typeof import('./../src/components/app/App-Header.vue')['default']
    AppSidebar: typeof import('./../src/components/app/App-Sidebar.vue')['default']
    Button: typeof import('./../src/components/widgets/Button.vue')['default']
    ButtonIcon: typeof import('./../src/components/widgets/Button-Icon.vue')['default']
    'ButtonIcon copy': typeof import('./../src/components/widgets/Button-Icon copy.vue')['default']
    ButtonImage: typeof import('./../src/components/widgets/Button-Image.vue')['default']
    ButtonSidebar: typeof import('./../src/components/widgets/Button-Sidebar.vue')['default']
    ButtonSlot: typeof import('./../src/components/widgets/Button-Slot.vue')['default']
  }
}

export { }
