// generated by unplugin-vue-components
// We suggest you to commit this file into source control
// Read more: https://github.com/vuejs/vue-next/pull/3399

declare module 'vue' {
  export interface GlobalComponents {
    AppFloatingSidebar: typeof import('./../src/components/app/App-FloatingSidebar.vue')['default']
    AppFooter: typeof import('./../src/components/app/App-Footer.vue')['default']
    AppHeader: typeof import('./../src/components/app/App-Header.vue')['default']
    AppSidebar: typeof import('./../src/components/app/App-Sidebar.vue')['default']
    Bar: typeof import('./../src/components/charts/Bar.vue')['default']
    ChartBar: typeof import('./../src/components/charts/ChartBar.vue')['default']
    ChartLine: typeof import('./../src/components/charts/ChartLine.vue')['default']
    Details: typeof import('./../src/components/forms/companies/create-clients/details.vue')['default']
    FormCompaniesCreateclientsDetails: typeof import('./../src/components/forms/superadmin/companies/form-companies-createclients-details.vue')['default']
    FormCompaniesCreateclientsLicenses: typeof import('./../src/components/forms/superadmin/companies/form-companies-createclients-licenses.vue')['default']
    FormCompaniesCreateclientsRaffles: typeof import('./../src/components/forms/superadmin/companies/form-companies-createclients-raffles.vue')['default']
    FormCompaniesCreateclientsSecurity: typeof import('./../src/components/forms/superadmin/companies/form-companies-createclients-security.vue')['default']
    FormCompaniesCreateclientsTickets: typeof import('./../src/components/forms/superadmin/companies/form-companies-createclients-tickets.vue')['default']
    FormCompaniesMonitoring: typeof import('./../src/components/forms/superadmin/companies/form-companies-monitoring.vue')['default']
    FormCompaniesRaffles: typeof import('./../src/components/forms/superadmin/companies/form-companies-raffles.vue')['default']
    FormCreateclientsDetails: typeof import('./../src/components/forms/companies/create-clients/form-createclients-details.vue')['default']
    FormCreateclientsLicenses: typeof import('./../src/components/forms/companies/create-clients/form-createclients-licenses.vue')['default']
    FormCreateclientsRaffles: typeof import('./../src/components/forms/companies/create-clients/form-createclients-raffles.vue')['default']
    FormCreateclientsSecurity: typeof import('./../src/components/forms/companies/create-clients/form-createclients-security.vue')['default']
    FormCreateclientsTickets: typeof import('./../src/components/forms/companies/create-clients/form-createclients-tickets.vue')['default']
    FormLayout: typeof import('./../src/layouts/FormLayout.vue')['default']
    Licenses: typeof import('./../src/components/forms/companies/create-clients/licenses.vue')['default']
    Line: typeof import('./../src/components/charts/Line.vue')['default']
    MinTabs: typeof import('./../src/components/widgets/min-tabs.vue')['default']
    Monitoring: typeof import('./../src/components/forms/companies/monitoring.vue')['default']
    Raffles: typeof import('./../src/components/forms/companies/raffles.vue')['default']
    Security: typeof import('./../src/components/forms/companies/create-clients/security.vue')['default']
    SubPageLayout: typeof import('./../src/layouts/SubPageLayout.vue')['default']
    Tickets: typeof import('./../src/components/forms/companies/create-clients/tickets.vue')['default']
  }
}

export { }
