// generated by unplugin-vue-components
// We suggest you to commit this file into source control
// Read more: https://github.com/vuejs/vue-next/pull/3399

declare module 'vue' {
  export interface GlobalComponents {
    Header_: typeof import('./src/components/Header/_.vue')['default']
    Hello: typeof import('./src/components/Hello.vue')['default']
  }
}

export { }
