// generated by unplugin-vue-components
// We suggest you to commit this file into source control
// Read more: https://github.com/vuejs/vue-next/pull/3399

declare module 'vue' {
  export interface GlobalComponents {
    AppContent: typeof import('./../src/components/app/Content.vue')['default']
    AppFloatingSidebar: typeof import('./../src/components/app/FloatingSidebar.vue')['default']
    AppFooter: typeof import('./../src/components/app/Footer.vue')['default']
    AppHeader: typeof import('./../src/components/app/Header.vue')['default']
    AppMain: typeof import('./../src/components/app/Main.vue')['default']
    AppSidebar: typeof import('./../src/components/app/Sidebar.vue')['default']
    ChartsBar: typeof import('./../src/components/charts/Bar.vue')['default']
    ChartsLine: typeof import('./../src/components/charts/Line.vue')['default']
    SuperadminCompaniesCreateClientsFormsDetails: typeof import('./../src/components/superadmin/companies/create-clients/forms/details.vue')['default']
    SuperadminCompaniesCreateClientsFormsLicenses: typeof import('./../src/components/superadmin/companies/create-clients/forms/licenses.vue')['default']
    SuperadminCompaniesCreateClientsFormsRaffles: typeof import('./../src/components/superadmin/companies/create-clients/forms/raffles.vue')['default']
    SuperadminCompaniesCreateClientsFormsSecurity: typeof import('./../src/components/superadmin/companies/create-clients/forms/security.vue')['default']
    SuperadminCompaniesCreateClientsFormsTickets: typeof import('./../src/components/superadmin/companies/create-clients/forms/tickets.vue')['default']
  }
}

export { }
