// generated by unplugin-vue-components
// We suggest you to commit this file into source control
// Read more: https://github.com/vuejs/vue-next/pull/3399

declare module 'vue' {
  export interface GlobalComponents {
    AppFloatingSidebar: typeof import('./../src/components/app/FloatingSidebar.vue')['default']
    AppFooter: typeof import('./../src/components/app/Footer.vue')['default']
    AppHeader: typeof import('./../src/components/app/Header.vue')['default']
    AppSidebar: typeof import('./../src/components/app/Sidebar.vue')['default']
    ChartsBar: typeof import('./../src/components/charts/Bar.vue')['default']
    ChartsLine: typeof import('./../src/components/charts/Line.vue')['default']
    FormsCreateClientsDetails: typeof import('./../src/components/forms/create-clients/details.vue')['default']
    FormsCreateClientsLicenses: typeof import('./../src/components/forms/create-clients/licenses.vue')['default']
    FormsCreateClientsRaffles: typeof import('./../src/components/forms/create-clients/raffles.vue')['default']
    FormsCreateClientsSecurity: typeof import('./../src/components/forms/create-clients/security.vue')['default']
    FormsCreateClientsTickets: typeof import('./../src/components/forms/create-clients/tickets.vue')['default']
  }
}

export { }
