// generated by unplugin-vue-components
// We suggest you to commit this file into source control
// Read more: https://github.com/vuejs/vue-next/pull/3399

declare module 'vue' {
  export interface GlobalComponents {
    AppFloatingSidebar: typeof import('./../src/components/app/FloatingSidebar.vue')['default']
    AppFooter: typeof import('./../src/components/app/Footer.vue')['default']
    AppHeader: typeof import('./../src/components/app/Header.vue')['default']
    AppSidebar: typeof import('./../src/components/app/Sidebar.vue')['default']
    ChartsBar: typeof import('./../src/components/charts/Bar.vue')['default']
    ChartsLine: typeof import('./../src/components/charts/Line.vue')['default']
    FormsCompaniesCreateClientsDetails: typeof import('./../src/components/forms/companies/create-clients/details.vue')['default']
    FormsCompaniesCreateClientsLicenses: typeof import('./../src/components/forms/companies/create-clients/licenses.vue')['default']
    FormsCompaniesCreateClientsRaffles: typeof import('./../src/components/forms/companies/create-clients/raffles.vue')['default']
    FormsCompaniesCreateClientsSecurity: typeof import('./../src/components/forms/companies/create-clients/security.vue')['default']
    FormsCompaniesCreateClientsTickets: typeof import('./../src/components/forms/companies/create-clients/tickets.vue')['default']
    FormsCompaniesMonitoring: typeof import('./../src/components/forms/companies/monitoring.vue')['default']
    FormsCompaniesRaffles: typeof import('./../src/components/forms/companies/raffles.vue')['default']
  }
}

export { }
