// generated by unplugin-vue-components
// We suggest you to commit this file into source control
// Read more: https://github.com/vuejs/vue-next/pull/3399

declare module 'vue' {
  export interface GlobalComponents {
    AppHeader: typeof import('./../src/components/App/App-Header.vue')['default']
    AppSidebar: typeof import('./../src/components/App/App-Sidebar.vue')['default']
    ChartBar: typeof import('./../src/components/Charts/Chart-Bar.vue')['default']
    ChartLine: typeof import('./../src/components/Charts/Chart-Line.vue')['default']
    ConfigurarTickets: typeof import('./../src/components/Forms/ConfigurarTickets.vue')['default']
    CrearClientes: typeof import('./../src/components/Forms/CrearClientes.vue')['default']
    PlanesYLicencias: typeof import('./../src/components/Forms/PlanesYLicencias.vue')['default']
    PreguntasDeSeguridad: typeof import('./../src/components/Forms/PreguntasDeSeguridad.vue')['default']
    SorteosAutomaticos: typeof import('./../src/components/Forms/SorteosAutomaticos.vue')['default']
  }
}

export { }
