// generated by unplugin-vue-components
// We suggest you to commit this file into source control
// Read more: https://github.com/vuejs/vue-next/pull/3399

declare module 'vue' {
  export interface GlobalComponents {
    AppFooter: typeof import('./../src/components/app/App-Footer.vue')['default']
    AppHeader: typeof import('./../src/components/app/App-Header.vue')['default']
    AppSidebar: typeof import('./../src/components/app/App-Sidebar.vue')['default']
    AvatarIcon: typeof import('./../src/components/widgets/Avatar-Icon.vue')['default']
    ButtonCta: typeof import('./../src/components/widgets/Button-Cta.vue')['default']
    ButtonIcon: typeof import('./../src/components/widgets/Button-Icon.vue')['default']
    ButtonSidebar: typeof import('./../src/components/widgets/Button-Sidebar.vue')['default']
    CardRevenue: typeof import('./../src/components/widgets/Card-Revenue.vue')['default']
    CardSales: typeof import('./../src/components/widgets/Card-Sales.vue')['default']
    CardSalesRevenue: typeof import('./../src/components/widgets/Card-SalesRevenue.vue')['default']
    CardStats: typeof import('./../src/components/widgets/Card-Stats.vue')['default']
    WelcomeTile: typeof import('./../src/components/widgets/Welcome-Tile.vue')['default']
  }
}

export { }
